const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("outreach", {
  getState: () => ipcRenderer.invoke("state:get"),
  getSettings: () => ipcRenderer.invoke("settings:get"),
  saveSettings: (s) => ipcRenderer.invoke("settings:save", s),
  importLeads: () => ipcRenderer.invoke("leads:importDialog"),
  runAudit: () => ipcRenderer.invoke("run:audit"),
  runDraft: () => ipcRenderer.invoke("run:draft"),
  runOverride: (email) => ipcRenderer.invoke("run:override", email),
  findLeads: (params) => ipcRenderer.invoke("leadgen:search", params),
  setDraft: (params) => ipcRenderer.invoke("lead:setDraft", params),
  setFlaws: (params) => ipcRenderer.invoke("lead:setFlaws", params),
  redraftLead: (email) => ipcRenderer.invoke("lead:redraft", email),
  addFinding: (params) => ipcRenderer.invoke("lead:addFinding", params),
  addLead: (params) => ipcRenderer.invoke("lead:add", params),
  quickSend: (params) => ipcRenderer.invoke("lead:quickSend", params),
  setNote: (params) => ipcRenderer.invoke("lead:note", params),
  setTags: (params) => ipcRenderer.invoke("lead:tag", params),
  suppressLead: (params) => ipcRenderer.invoke("lead:suppress", params),
  unsuppressLead: (email) => ipcRenderer.invoke("lead:unsuppress", email),
  bulkDelete: (emails) => ipcRenderer.invoke("lead:bulkDelete", emails),
  deleteLead: (params) => ipcRenderer.invoke("lead:delete", params),
  verifyLeads: (params) => ipcRenderer.invoke("leads:verify", params),
  exportLeads: (params) => ipcRenderer.invoke("leads:exportDialog", params),
  fbGenerateDrafts: (params) => ipcRenderer.invoke("fb:generateDrafts", params),
  fbMarkSent: (email) => ipcRenderer.invoke("fb:markSent", email),
  fbMarkSkipped: (email) => ipcRenderer.invoke("fb:markSkipped", email),
  fbOpenLink: (url) => ipcRenderer.invoke("fb:openLink", url),
  scheduleCreate: (params) => ipcRenderer.invoke("schedule:create", params),
  scheduleList: () => ipcRenderer.invoke("schedule:list"),
  scheduleCancel: (id) => ipcRenderer.invoke("schedule:cancel", id),
  onScheduleFired: (cb) => ipcRenderer.on("schedule:fired", (_e, entry) => cb(entry)),
  checkForUpdates: () => ipcRenderer.invoke("update:check"),
  onUpdateStatus: (cb) => ipcRenderer.on("update:status", (_e, s) => cb(s)),
  restartToUpdate: () => ipcRenderer.invoke("update:restart"),
  runSend: (dryRun) => ipcRenderer.invoke("run:send", { dryRun }),
  sendOne: (key) => ipcRenderer.invoke("lead:sendOne", key),
  runFollowup: (dryRun) => ipcRenderer.invoke("run:followup", { dryRun }),
  runInbox: () => ipcRenderer.invoke("run:inbox"),
  openReport: () => ipcRenderer.invoke("report:open"),
  installBrowser: () => ipcRenderer.invoke("browser:install"),
  onLog: (cb) => ipcRenderer.on("engine:log", (_e, chunk) => cb(chunk)),
  onDone: (cb) => ipcRenderer.on("engine:done", (_e, info) => cb(info)),
});
